### ISSUE TITLE
Super high CPU usage for 'Nylas Mail Helper'

### ISSUE THREAD

**Issue by Joe8Bit** [nylas/nylas-mail#3178]
Seeing very high CPU usage for 'Nylas Mail Helper' on OSX `10.11.2`. See screenshot.

![image](https://cloud.githubusercontent.com/assets/467683/22031868/0075f20c-dcda-11e6-8b71-62b3e6fa8623.png)

Consistently at 80%+, frequently bursting to <100% and bursting over at startup. Makes computer virtually unusable.

Think this is a renamed `Electron Helper` and to check, I have quit and restarted (the OS and apps) any other current running Electron apps (e.g Slack). It has no effect.

##### Are there any related issues?
https://github.com/nylas/N1/issues/2068

##### What operating system are you using?
`OSX 10.11.2`

##### What version of N1 are you using?
`1.0.8`

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plugins, fresh install today.
 
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't think so, but I have a gmail and a g apps account created.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes, reproducible on Macbook (2016) and MacBook Pro (2016) using same OSX version with fresh install.

**Comment by emorikawa** [comment]
@Joe8Bit One of those processes is the background local sync engine. That should run fairly hot during initial sync as we download, process, and save all of your messages. We're actively working on reducing processor consumption there.

The 2nd process is the main window. It should only have significant CPU utillization when you're actively using the app, or scrolling through, etc.

**Comment by Joe8Bit** [comment]
Thanks for the fast response @emorikawa, that makes sense. Couple of notes:

* It *seems* like initial sync has finished (not sure how to confirm) and CPU usage remains high (even after system and app restart)
* Both remain high regardless of active window, neither dropped below 65% in the last couple hours despite active/inactive windows

Is that expected behaviour?

**Comment by grinich** [comment]
How much mail do you have?

**Comment by Joe8Bit** [comment]
Currently have 25,000 messages (+/-) across two mailboxes. Unread count <20 across both.

**Comment by aarontyree** [comment]
Same experience as @Joe8Bit. Sync seems to have completed, but still hitting 90% CPU usage spikes. Already sold on Nylas though:)

**Comment by Joe8Bit** [comment]
Short update. App (version `1.0.8`) open for 24 hours, as an inactive application. Average CPU load across *both* `Nylas Mail Helper` processes in that time 85-90% according to Activity Monitor.

**Comment by wolfskaempf** [comment]
I experience the same problem under the same conditions as @Joe8Bit. Left it open for around 20 hours at this point.

Additionally, it seems like Mail Synchronisation has stopped at November 2009. Gmail counts about 40,000 messages in my account, however, most of them came in between 2014 and today.

**Comment by deyil** [comment]
Same here. Excessive resources use (CPU and memory) making my Mac slow, as you can see and in attachments. Sync now runs at least 30 min, so I can't work easily on my Mac

![screen shot 2017-01-18 at 12 57 17](https://cloud.githubusercontent.com/assets/872880/22061580/33956376-dd7e-11e6-8ac8-c0679c1b29bc.png)

![screen shot 2017-01-18 at 12 57 14](https://cloud.githubusercontent.com/assets/872880/22061581/33986c06-dd7e-11e6-9dbb-4dbe1584811c.png)

**Comment by maxskybarger** [comment]
I too am having the same results.

**Comment by camflan** [comment]
I'm experiencing the same thing, CPU usage nearing 200% for long periods of time - I have no idea how long this will take, there's no progress indicator. I have ~ 65,000 mail messages.

**Comment by deyil** [comment]
I had to remove Nylas since the app and Mac were not responding. I don't see the point of syncing all emails and not only the most recent ones as IMAP does. Syncing will take forever...

**Comment by aarontyree** [comment]
It took longer than I expected for everyting to sync. But after about two hours, CPU use is down to normal for me. Sent from Nylas Mail
          
            
            On Jan 18 2017, at 9:54 am, Demetris <notifications@github.com> wrote:
            
            
              I had to remove Nylas since the app and Mac were not responding. I don't see the point of syncing all emails and not only the most recent ones as IMAP does. Syncing will take forever...

**Comment by maxskybarger** [comment]
Like many others, once my mailbox finished syncing, the CPU spike ended.

**Comment by grinich** [comment]
Is anyone else seeing high CPU after their initial mailbox sync completes?

**Comment by mrgabefox** [comment]
Also experiencing this issue. At this point it is between 99%-111% CPU at all times. Unusable. 

Fresh install as of yesterday, updated today to 1.0.9. on OSX 10.11.6.

**Comment by grinich** [comment]
@mrgabefox But has your initial sync completed?

Every mail client spikes CPU usage during initial sync since it is processing thousands upon thousands of items.

Try syncing via Mail.app on your Mac. It will also have ~100% CPU usage or more.

**Comment by mrgabefox** [comment]
@grinich Thank you for the insanely quick response. 
Totally get it. It appears that it is still syncing - everything is done except one mailbox's spam folder (409 total messages). It's been stuck on that folder for over 3 hours. Somehow knocked out the other ~9k emails from my inboxes in less than an hour.

**Comment by midN** [comment]
@grinich - I've got similar problem with local-sync. But mine local-sync is failing hard for some reason after i added IMAP account, it's throwing errors during Syncing.
Therefore CPU goes instantly 100%, local-sync keeps retrying the same error and Nylas Mail becomes so unresponsive that i cannot even delete that Account anymore.

**Comment by deyil** [comment]
> Every mail client spikes CPU usage during initial sync since it is processing thousands upon thousands of items.
> 
> Try syncing via Mail.app on your Mac. It will also have ~100% CPU usage or more.
> 

@grinich Mail.app Never froze my Mac even when I tried to sync 3 accounts at the same time, while Nylas made my work's Mac unusable even with 1 account trying to sync. Nylas is very promising, but this issue had me remove it because I couldn't work. I never had an app freeze my Mac that bad and for that time!

As I said before whats the need to sync all emails and not the most recent one?! It is a waste of resources

@midN When I killed helper, the sync was corrupted and I have to reset accounts to fix Nylas

**Comment by grinich** [comment]
Nylas Mail is designed to sync recent mails first and also prioritize you Inbox folder. After that, it will sync older messages.

**Comment by jstejada** [comment]
@midN what kind of errors are you getting?

**Comment by jstejada** [comment]
@mrgabefox can you open the activity window via `cmd+alt+w`? if so, can you open dev tools Console via `cmd+alt+i`? do you see any errors there?

if you restart Nylas Mail, does it get unstuck from that folder?

**Comment by jstejada** [comment]
Hi all! We're releasing a fix today that will fix an error that caused the app to freeze and continue to use resources without syncing mail, and we think was causing a lot of the issues reported in this thread.

I will let you know as soon as we release 1.0.11. Thanks for your patience folks!

**Comment by jstejada** [comment]
Hi all! we've just released v 1.0.11. Let us know if you continue having issues!

**Comment by afturner** [comment]
I'm still having the same exact issues as everyone else here. I'm on 1.0.11. It says my mailbox is still syncing despite having left it open for >24 hours. I've tried adding and removing the accounts to no avail. The original Nylas didn't have these issues!

**Comment by talbet** [comment]
Also still having the same issue even after updating to 1.0.11. Has been syncing for 6+ hours. Updated from N1 where all mail boxes had been successfully synced.

**Comment by grinich** [comment]
Hi folks-- just because your mailbox has been syncing for "X hours" does not mean it's finished with the initial sync.

You can see details by clicking on this area in the lower left:

![image](https://cloud.githubusercontent.com/assets/92417/22179013/d3760e02-dffb-11e6-9013-05ebc605d423.png)

Completed folder syncs show as green circles like this: 
![image](https://cloud.githubusercontent.com/assets/92417/22179015/e9f97632-dffb-11e6-9d5e-57ddeb005eca.png)

Whereas incomplete folder syncs are open circles and hovering over them will show how far they have synced:
![image](https://cloud.githubusercontent.com/assets/92417/22179018/f3eb63c6-dffb-11e6-834f-aa4038ee24de.png)

Please comment if you are still having high CPU and all folders are finished aka filled in green circles.

**Comment by grinich** [comment]
Due to throttling from Gmail, it's not unusual for a full mailbox sync to take hours to several days. https://support.google.com/a/answer/1071518?hl=en

**Comment by talbet** [comment]
Ok, that makes sense and is good to know. I also realised that by hovering on a folder that is in progress you get a tooltip that shows how much information has been synced. It's always frustrating when you are not sure if the process is working or stuck, but the tooltip shows that progress is being made.

![screencapture](https://cloud.githubusercontent.com/assets/899827/22187970/a571b146-e163-11e6-82cc-9adb174d52c7.jpg)

**Comment by jstejada** [comment]
is anyone here seeing Nylas Mail freeze or not show mail, like n #3198? Just want to make sure that they aren't the same issue

**Comment by deyil** [comment]
I think this issue is solved. I don't see high CPU anymore.

**Comment by deyil** [comment]
@jstejada Yes I get the "Nylas Mail is offline" message

**Comment by afturner** [comment]
@jstejada @deyil I also get the offline message very frequently, as well as IMAP connection/authentication issues.

**Comment by jstejada** [comment]
we've released 1.0.15 with a few CPU performance improvements. let me know if folks are still seeing cpu problems!

**Comment by jstejada** [comment]
just a heads up that we will be releasing more cpu improvements this week courtesy of @mhahnenberg !

**Comment by jstejada** [comment]
hi everyone, 1.0.18 is out with a lot of CPU perf improvements. Let us know what you think!

**Comment by spang** [comment]
Closing this for now given the recent CPU improvements—please reopen if further issues encountered.

**Comment by LasseJacobs** [comment]
I am still having issues with nylas mail eating up my cpu and being stuck at 'syncing your mailbox'. It synced part of my mail box and now it is stuck at july of 2015. I left it running for at least 6 hours. The app looks great but unfortunately I can't use something that uses 40% of my cpu at idle.

**Comment by jstejada** [comment]
hi @LasseJacobs , can you try version 2.0.16? it has some more cpu usage improvements

**Comment by LasseJacobs** [comment]
@jstejada No sorry the problem remains.Still high CPU usage and as far as I can see in the 20 minutes I let it run for it did not make any progress syncing. Is there I way I can cancel the sync? Because I don't need my emails from 2015 and apart from that the app works fine. I recieve new emails and I am able to send emails perfectly fine.

**Comment by jstejada** [comment]
@LasseJacobs unfortunately there currently is no way to stop sync.

**Comment by skybluejay** [comment]
Hi there, I'm having this problem as well. The mail syncing with my gmail account has been running for 3 days now. I even created a filter in my gmail to delete messages more than a few years old but the syncing is still continuing and the Nylas Mail Helper is frequently showing up around 90% CPU in Activity Monitor. Any ideas on a way to fix please?

For reference, this is on an old (2009) Macbook Pro, 8G RAM and an SSD installed. I'm running OS X Mavericks. 
Any helpful advice would be much appreciated. Thanks!

**Comment by MichaelSchmidt82** [comment]
-- As a developer, I understand the need to index and the cost associated with it.  Good job guys

-- As a customer, I don't particularly like my laptop CPU to be at ~91C for hours on end.  ::mad face::

You should probably add a pause sync option.

**Comment by edarioq** [comment]
I have the same issue here. I was wondering why my Mac was losing battery so fast... this is the culprit. 

<img width="815" alt="screenshot 2017-08-25 15 43 52" src="https://user-images.githubusercontent.com/1882457/29731989-4821cd40-89ac-11e7-9875-990cffd57770.png">

**Comment by likwidgames** [comment]
Still happening in 2.0.32 using OSX 10.13.2

Has been using 112% CPU for the last 20 minutes. This did not happen a month ago. It's a shame, I have been really enjoying using this mail client.

**Comment by dev-michael-schmidt** [comment]
I just found out that Nylas is no longer maintained??

https://github.com/nylas/nylas-mail/issues/3564

I'm using mailspring as described in that post -- same author, same client, faster, no longer sponsored by nylas anymore.
