### ISSUE TITLE
When doing an initial IMAP sync, Nylas opens an increasing number of connections until the server reaches a connection limit and never finishes syncing.

### ISSUE THREAD

**Issue by nvahalik** [nylas/nylas-mail#3228]
Every time I have removed and re-added my IMAP account, it says "gathering folders" in the sync window but it never actually does anything. I'm using Dovecot hosted on a cPanel 12.x server. I can see the connections being made from my machine to the server. Over time the total number of open connections continues to rise until finally the maximum number of connections allowed user user/ip combination is reached... at which point Nylas says that it can no longer reconnect.

My IMAP Path Prefix is "INBOX".

##### Are there any related issues?
None that I'm aware of.

##### What operating system are you using?
OSX 10.11.6 (15G1217)

##### What version of N1 are you using?
1.0.15

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes, this happens every time I go through the addition of my IMAP account.

This is what happens when I occasionally check the `netstat` output on the server:
![root_vps___ _ssh_vps_ _108x125](https://cloud.githubusercontent.com/assets/632120/22353637/0b50bb80-e3e7-11e6-8907-eb68b165f681.jpg)

**Comment by jstejada** [comment]
hi @nvahalik we've pushed a fix for this and should be released next week!

**Comment by nvahalik** [comment]
I'm still having this issue. In fact, I'm thinking it actually happens faster now (that is, it opens more connections more quickly and never finishes syncing).

**Comment by jstejada** [comment]
thanks @nvahalik , reopening this issue to investigate

**Comment by namuit** [comment]
I have the same problem (OSX 10.12.1, Nylas Mail 1.0.21, IMAP folder structure with 4 levels)

**Comment by nvahalik** [comment]
FWIW, I don't have any folders except for the ones underneath the root...

**Comment by namuit** [comment]
FWIW, the mail server of my company is Dovecot as well with

```
tag OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SEARCH=FUZZY SPECIAL-USE COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk] Logged in
```

**Comment by sethwebster** [comment]
+1

**Comment by jstejada** [comment]
We're working on a fix for this!

**Comment by jstejada** [comment]
This should be fixed in version 1.0.30 which has just been released! Let me know if you continue having issues!
