### ISSUE TITLE
Unable to archive/perform action on message after replying to a thread

### ISSUE THREAD

**Issue by ryanleesipes** [nylas/nylas-mail#3290]
I receive this error when trying to archive messages: "Error message: Syncback Task Failed: All messages in a thread require an IMAP uid to perform an action"

##### Are there any related issues?
Seemingly, no.

##### What operating system are you using?
Elementary OS Loki (Ubuntu 16.04)

##### What version of Nylas Mail are you using?
1.0.28

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Activity List, Emoji Picker, Quick Replies, Translation, Link Tracking, Open Tracking

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Using Fastmail, not sure if it is specific to Fastmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No.

**Comment by jstejada** [comment]
Hey, thanks for the report! We're looking into this one. Are you sure you're on 1.0.28? That version hasn't been released.

**Comment by ryanleesipes** [comment]
@jstejada using a .deb I got from Sachin for testing (for my org) which has that version listed. Also, not sure if this is related, but I also get this error on sending an Email:
"Syncback Task Failed: Message contains bare newlines" 
(the window says it was sent, but says it could not move the Email to the sent folder).

If I need to create a different bug for that, I can do that.

**Comment by jstejada** [comment]
Bare newlines is a different issue #3251

**Comment by jstejada** [comment]
This should be fixed in version 1.0.30 which has just been released! Let me know if you continue having issues!

**Comment by ryanleesipes** [comment]
Still having the issue in 1.0.30, should I remove and re-add the account? Do you think that would make a difference?

**Comment by almet** [comment]
I am having the same issue here, I'm happy to provide more feedback on this if it is helpful. Thanks!

**Comment by claudioruiz** [comment]
merging into duplicate #3308
