### ISSUE TITLE
Error when marking as read -- All messages require UID error

### ISSUE THREAD

**Issue by monkeydri** [nylas/nylas-mail#3308]
I have an error with two custom IMAP accounts (mail.com and OVH), some emails cannot be marked as read. I have seen another issue related to mark as read problems (https://github.com/nylas/nylas-mail/issues/1298) however this is different as even after changing view or directory I still cannot mark the email as read. I have also seen the issue about sync problems (#781) but it has been closed.

```
Error

We were unable to apply the changes to your thread, please try again!
If the error persists, contact support@nylas.com with the error message.

Error message: All messages in a thread require an IMAP uid to perform an action
```

![nylas-mail-as-read-bug](https://cloud.githubusercontent.com/assets/18724661/23501506/64bbcb2a-ff34-11e6-90ff-e0b19c841bde.png)

- operating system : Mac - Sierra OS 10.12.3
- Nylas Mail version : v1.0.30.
- third-party plugins installed : none
- issue related to a specific email provider : happens with mail.com account and OVH account ( both IMAP).
- issue reproducibility : appears to happen on all new emails, but I'm not sure yet.

**Comment by cgorman** [comment]
I'm experiencing the same issues with my fastmail account.

* operating system : Mac - Sierra OS 10.12.3
* Nylas Mail version : v1.0.30.
* third-party plugins installed : none
* issue related to a specific email provider : Fastmail
* issue reproducibility : Happens on all e-mails so far if I mark as read/unread

**Comment by franzos** [comment]
I have the same issue, pretty much same config.

```
ChangeUnreadTask (ID: aa0b) FAILED (PROCESSING REMOTE) APIError 500 All messages in a thread require an IMAP uid to perform an action
{
  "_rememberedToCallSuper": true,
  "id": "local-8329828f-aa0b",
  "sequentialId": 1488977621799,
  "queueState": {
    "isProcessing": false,
    "localError": null,
    "localComplete": true,
    "remoteError": {
      "stack": "Error\n    at new APIError (/src/flux/errors.es6:29:19)\n    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:29:25)\n    at EventEmitter.eventHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)\n    at EventEmitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)\n    at Function.trigger (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)\n    at Function.functor [as didReceiveSyncbackRequestDeltas] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)\n    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/internal_packages/deltas/lib/delta-processor.es6:142:13)\n    at /internal_packages/deltas/lib/delta-processor.es6:80:12\n    at next (<anonymous>)\n    at step (/internal_packages/deltas/lib/delta-processor.es6:2:1)\n    at /internal_packages/deltas/lib/delta-processor.es6:2:1\n    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)\n    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)\n    at tryOnImmediate (timers.js:554:5)\n    at processImmediate [as _immediateCallback] (timers.js:533:5)",
      "name": "APIError",
      "error": {
        "stack": "Error: All messages in a thread require an IMAP uid to perform an action\n    at NylasError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/isomorphic-core/src/errors.js:2:1)\n    at APIError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/isomorphic-core/src/errors.js:18:5)\n    at Object.forEachFolderOfThread (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/client-sync/src/local-sync-worker/imap-helpers.js:16:13)\n    at MarkThreadAsRead.run (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/mark-thread-as-read.imap.js:26:23)",
        "message": "All messages in a thread require an IMAP uid to perform an action"
      },
      "body": {
        "message": "All messages in a thread require an IMAP uid to perform an action"
      },
      "requestOptions": null,
      "statusCode": 500,
      "message": "All messages in a thread require an IMAP uid to perform an action"
    },
    "remoteAttempts": 1,
    "remoteComplete": false,
    "status": "FAILED",
    "debugStatus": "PROCESSING REMOTE"
  },
```

**Comment by jstejada** [comment]
Thanks! We're looking into this one

**Comment by druizz** [comment]
In my case, I experience the issue when one of the mails in the thread is duplicated (see attached image, last two elements are the same, duplicated). I cannot archive nor delete the thread, and even if I archive it in Gmail web and reload, the thread is still there, unread.
This duplication happens sporadically, hard to reproduce.

<img width="109" alt="captura de pantalla 2017-03-16 a las 15 57 20" src="https://cloud.githubusercontent.com/assets/26308910/24002850/13a255f4-0a62-11e7-84e5-76f50fb7f380.png">

- operating system : Mac - Sierra OS 10.12.3
- Nylas Mail version : v1.0.39.
- third-party plugins installed : none
- issue related to a specific email provider : Gmail
- issue reproducibility : Happens when thread has duplicate elements

**Comment by scottkf** [comment]
I'm experiencing the same as @druizz. I have a duplicate email in the thread. I got rid of it via gmail and it still shows, but I've only had this happen on one thread.

- Operating system : Mac - Sierra OS 10.12.3
- Nylas Mail version : v1.0.39.
- Third-party plugins installed : none
- Issue related to a specific email provider : Gmail
- Issue reproducibility : Happens when thread has duplicate elements

**Comment by MattSNZ** [comment]
I have the same thing happen, but it's only ever with one contact. It's happening almost every day lately. To fix it, I've been deleting the app cache and reinstalling but that's annoying as hell to do every day.

- Operating system : Mac - Sierra OS 10.12.3
- Nylas Mail version : v1.0.39.
- Third-party plugins installed : none
- Issue related to a specific email provider : Gmail
- Issue reproducibility : Happens when thread has duplicate elements

**Comment by jstejada** [comment]
This should be fixed in our latest release!

**Comment by franzos** [comment]
@jstejada big thanks! :+1:

**Comment by almet** [comment]
I have 2.0.10 installed and still face the issue. @jstejada , is it supposed to be fixed with this release or is it in a next one? Thanks!

**Comment by bongoman** [comment]
I'm experiencing this issue with Nylas 2.0.15 when I attempt to un-star messages — this is with a Fastmail account.

**Comment by franzos** [comment]
@bongoman can you easily reproduce this issue (star, un-star messages) or does this only happen occasionally? In case it only happens occasionally, it may be worth resetting your Email cache.

_Nylas Mail > General > Reset Email Cache_

**Comment by jstejada** [comment]
Reopening given that there are still reports. We're looking into it!

**Comment by owain68** [comment]
Yes I have exactly this issue on 2.0.15  on MacOS Sierra 10.12.4 using solely Gmail accounts.

**Comment by tpaixao** [comment]
I have the same error on a normal IMAP account using Nylas 2.0.16 on Windows 7.

**Comment by roja45** [comment]
same issue, Imap account, 2.0.16, windows 10

**Comment by jbbr** [comment]
same issue, GMail, 2.0.18, linux, official deb build

**Comment by jonsurfs** [comment]
Same issue, MacOS, Rackspace email.

**Comment by Melissa-Kay** [comment]
Same issue, even after updating to yesterday's release (2.0.28). 

"Error
We were unable to apply the changes to your thread, please try again later.
Error message: All messages in a thread require an IMAP uid to perform an action"

**Comment by tongnk** [comment]
Sam issue. MacOS Sierra 10.12.4, G-Suite

**Comment by jonsurfs** [comment]
I think that this is actually caused (for me, at least) on the initial sync
of my account (which has been going for 24 hours on my account, but there
are a lot of emails in there). I've noticed that, as folders sync, it then
lets me move things around without issue (I have one email left that still
gives me the error).

**Comment by deonjo** [comment]
Quick Fix: Remove email account with the problem through the preference panel and re-add the account. After the initial sync, the problem disappeared.

**Comment by cmoro-deusto** [comment]
Count me in.
Linux release, v2.0.32, with a Fastmail account. Happened in earlier versions as well.

**Comment by EliBon** [comment]
Hi there, I just started using Nylas mail on friday, and encountered this bug today. Any news on a fix?

**Comment by compiaffe** [comment]
Same here with v2.0.32 on Fedora and an IMAP account.

**Comment by tezer** [comment]
Same on Ubuntu 17.04, Nylas version 2.0.31

**Comment by mradamwood** [comment]
Still a problem for me too. 

MacOS Sierra 10.12.5
Nylas 2.0.32

Only one thread, last two emails in the thread are duplicates. Shows as archived in Gmail and not duplicate message.

**Comment by johnramsden** [comment]
I'm still getting this with a single FastMail account. NixOS 17.03, Nylas 2.0.32.

**Comment by Bergg** [comment]
Happening to me as of today Nylas 2.0.31 on Fedora using an IMAP account.

**Comment by theurso** [comment]
Happening to me as well with Windows 10 Pro 1703, Nylas 2.0.32, using Fastmail.

**Comment by OmarMorando** [comment]
Happening to me with Kubuntu 17.10 and Nylas 2.0.32 using IMAP account.

**Comment by Melissa-Kay** [comment]
This continuing to happen to me. 6 emails total... 4 of which were in the last 2 days. If it helps.. this seems to only be happening when I send an email with my company email alias cc'd (think support@). Support emails also go to in my inbox. So whenever I send an email with support@ cc'd, it goes into my inbox as a new message, and that's when the chain gets flagged with this error.

**Comment by Bergg** [comment]
reacting on @Melissa-Kay 's message: I can't figure out a pattern on my side. I have one account and it seems to happen randomly. It worked fine this morning, and now the issue shows up again this afternoon.

**Comment by alexandru-calinoiu** [comment]
I have the same issue with `2.0.31` and gmail.

Archive and delete won't work I am able to do this actions from the gmail client.

**Comment by claudioruiz** [comment]
Happen to me as well. 
Version 2.0.32 (2.0.32) on OSX Sierra.

**Comment by prajwalrao** [comment]
I have the same issue as well..

Operating system -  **Mac Sierra OS 10.12.5**
Nylas Mail version  - **v2.0.32 (2.0.32)**
Third-party plugins installed - **n1-avatars**, **Taiga theme**
Issue related to a specific email provider  - **Office(ActiveExchange) IMAP acct**.

**Comment by fauckenthaler** [comment]
same thing here.
nylas v2.0.32
latest sierra

**Comment by ASAPHAANING** [comment]
Ubuntu 16.04 x64 Nylas 2.0.32. Also on Windows 10 x64.

**Comment by Bergg** [comment]
A workaround for IMAP which I found works for me : add another post in the thread (like forwarding it to yourself) and then the email can be handled (moved, deleted, archived,..) again.

**Comment by kareem** [comment]
Same thing here.
Nylas 2.0.32, Sierra 10.12.1, Fastmail

**Comment by grimen** [comment]
Same here on Nylas 2.0.32 (Sierra). Amazed this is not resolved for paying users fast, kind of ignorant - renders the client so buggy I thinking of swtiching.

**Comment by kareem** [comment]
Agreed w/ @grimen -- it's been three months. Would love to at least see an update from the Nylas team.  I've switched away because this issue is so painful.

**Comment by johnramsden** [comment]
@kareem I concur, I was initially really excited about the project but the lack of support lately has meant I've decided to cease assisting the project as a paying user. I had been paying the past few months even though there was no extra functionality for paying users because I like the project, but it has been unusable for me since this problem. 

I've moved back to trusty Thunderbird where at least I can send messages. Maybe I'll switch back in the future if the project returns to being supported.

**Comment by giltee** [comment]
Started using Nylas, really like the gui but this issue is really painful. Is it ever going to be fixed? Can't see myself paying for the service with this bug outstanding.

**Comment by j-rahman** [comment]
I confirm this bug with Nylas Mail version 2.0.32 on Xubuntu 16.04 LTS.

**Comment by qaraclemente** [comment]
Also experiencing this issue on Nylas 2.0.32 on macOS Sierra 10.12.5.

**Comment by nextlevelshit** [comment]
In my case:
> GNU/Linux ubuntu 17.04

helped that:
```bash
sudo apt-get install
```
and (re)installing the newest version of Nylas Mail v2.0.32: [Download Nylas .deb v2.0.32](https://edgehill.nylas.com/download?platform=linux-deb)

**Comment by allen-n** [comment]
Experiencing this issue on Nylas 2.0.32 on Windows Version 10.0.15063 Build 15063, with a gmail account, seems to have been triggered by any conversation thread, giving the following error: 
![image](https://user-images.githubusercontent.com/30642496/28854358-9d8335b8-76eb-11e7-893f-d49d9172c838.png)

**Comment by RommelTJ** [comment]
Got issue on Nylas 2.0.32 on macOS Sierra 10.12.6, on a GSuite account. 
NylasMail > Preferences > General > Reset Email Cache resolved the issue for me.

**Comment by aindraus** [comment]
Any updates on this issue? I really don't want to switch email client but now this issue is becoming annoying.

**Comment by kareem** [comment]
I've switched to Astro.  It's faster, cleaner, and much better supported than Nylas.

**Comment by Bergg** [comment]
sadly astro only supports gmail and office365, I need exchange or at least imap/smtp..

**Comment by johnramsden** [comment]
@kareem @Bergg and no Linux support.

**Comment by AaronMcConkey** [comment]
Preferences --> Reset Email Cache seems to have resolved this for me as well (fingers crossed to sticks!)
G Suite, macOS.

**Comment by johnhamelink** [comment]
I was able to replicate this by forwarding an email from one account to another (Fastmail -> Office365) and then deleting the original email (both accounts being connected to Nylas Mail). Resetting the Email cache fixes this.
