### ISSUE TITLE
Your NylasID is invalid. Please log out then log back in.

### ISSUE THREAD

**Issue by clayton** [nylas/nylas-mail#3325]
##### Are there any related issues?

Not that I could find.

##### What operating system are you using?

MacOS 10.12.3 (16D32)

##### What version of Nylas Mail are you using?

1.0.32

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

Ido theme

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Not sure, possibly Fastmail (specifically SMTP.)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

After having a couple messages fail to send from my Fastmail account, I toggled the debug flags by selecting "Run with Debug flags" from the "Developer" menu. Now, when Nylas launches I am greeted with an error dialog that says:

**Your NylasID is invalid. Please log out then log back in.**
Actions like sending and receiving mail require this token. Please log back into your Nylas ID to restore it—your email accounts will not be removed in this process.
[Log Out]

I have attempted to login, and even changed my password, but I cannot get passed the Nylas ID login scene.

![screen shot 2017-03-13 at 8 10 34 am](https://cloud.githubusercontent.com/assets/6334/23860580/9e7880f4-07c4-11e7-9361-9ac2ae2490da.png)

![screen shot 2017-03-13 at 8 10 37 am](https://cloud.githubusercontent.com/assets/6334/23860589/a37e3daa-07c4-11e7-912f-7def56341654.png)

After clicking the "Log out" button on the system dialog, it immediately reappears. This happens four times in a row before it seems like Nylas restarts (the login window goes away) and then the process starts all over again. Nylas will only quit when force quit.

I tried removing everything in `~/Library/Application\ Support/Nylas\ Mail` which had no effect.

**Comment by clayton** [comment]
Update: I also tried completely removing Nylas (using AppZapper,) downloading it again and re-installing. Still experiencing the same issue. I also receive the same error when attempting to install from the homebrew cask.

**Comment by jstejada** [comment]
Hi @clayton, sorry to hear this. As a temprary solution, can you try removing your `~/.nylas-mail` folder? This should restore the app.

Really sorry for the trouble, we're going to look into what's causing this

**Comment by JCummings01** [comment]
I experienced the same issue and the only solution that makes the app usable again is to delete the ~/nylas-mail folder and go through the app setup process from the beginning.

**Comment by briandant** [comment]
My issue seems to be exactly the same as @clayton. As soon as I turn on debugging, that message pops up. OS X Version: `10.11.6`

**Comment by patrickmaas** [comment]
I got the same issue after an application restart when I switched on the debug mode. Hope that helps somehow.

**Comment by jstejada** [comment]
This should be gixed in the next release!

**Comment by jstejada** [comment]
This should be fixed in 1.0.39

**Comment by abishekrsrikaanth** [comment]
On 1.0.39, but still have the same issue.

![image](https://cloud.githubusercontent.com/assets/1639302/23977605/5ae9f25c-09c5-11e7-8dbb-e92a6b6dd470.png)

**Comment by jbbr** [comment]
Got this today too in 2.0.32

After clicking "Logout" I got:

```
Password Management Error
We couldn't store your password securely! For more information, visit https://support.nylas.com/hc/en-us/articles/223790028
```

After re-login:
![screenshot from 2017-05-10 16-17-03](https://cloud.githubusercontent.com/assets/682607/25903253/2b8e230e-359c-11e7-8217-7ff76c44f9cc.png)

**Comment by portwaypoint** [comment]
Yep, got this one this morning too after returning to work after the weekend. :-(

**Comment by portwaypoint** [comment]
Yes, I'm getting that as well. No accounts appear to be broken in the list, but the above message, still keeps appearing. I may even be actually getting all mails even with the nag (false positive failure condition perhaps).

**Comment by dportalesr** [comment]
Any solution on this yet?

I suddenly got this notice:
![image](https://user-images.githubusercontent.com/237597/39383299-6b05fe60-4a2e-11e8-86e5-d71fe52fc1ec.png)
and then my Nylas session is destroyed and it asks me to login, but as soon as I do that, I get the notice and I'm unable to login.

After a few of these incidents (not my first time), I think it may be somehow related to the fact that I'm using an email account (that is registered in Nylas) as a Github login, and when asked for the keychain password for it (when pushing code for example) failing at providing the correct password (I keep forgetting it 😅) will seemingly trigger this problem short after. Still, not 100% sure they're related but maybe the OS keychain is what connects these issues.

Using: Mac OS HighSierra 10.13.3 (17D102)

**Comment by tastyminerals** [comment]
After working for couple of days Nylas started to throw the same error on Manjaro Linux :(
